/* export.js — real downloadable artefacts: a valid .xlsx (zip of XML, stored/uncompressed), a markdown vault, and a printable HTML report. */
import { getProject, getProjectDocs, getProjectExtractions, projectStats, projectCost, getChapter, getBook } from './store.js';
const storeRef = { getBook };
import { quotePlain } from './seed.js';
import { SDG_TITLES, fmtLongDate, esc, fmtCost } from './ui.js';

/* ---------- minimal ZIP writer (stored, no compression) ---------- */
const crcTable = (() => { const t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; } return t; })();
function crc32(bytes) { let c = 0xFFFFFFFF; for (let i = 0; i < bytes.length; i++) c = crcTable[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; }
function zipStored(files) {
  const enc = new TextEncoder();
  const parts = []; const central = []; let offset = 0;
  const dosTime = 0x0000, dosDate = 0x5A21; // fixed timestamp
  for (const [name, content] of files) {
    const nameB = enc.encode(name); const data = typeof content === 'string' ? enc.encode(content) : content;
    const crc = crc32(data);
    const local = new DataView(new ArrayBuffer(30));
    local.setUint32(0, 0x04034b50, true); local.setUint16(4, 20, true); local.setUint16(6, 0x0800, true); local.setUint16(8, 0, true);
    local.setUint16(10, dosTime, true); local.setUint16(12, dosDate, true); local.setUint32(14, crc, true); local.setUint32(18, data.length, true); local.setUint32(22, data.length, true);
    local.setUint16(26, nameB.length, true); local.setUint16(28, 0, true);
    parts.push(new Uint8Array(local.buffer), nameB, data);
    const cd = new DataView(new ArrayBuffer(46));
    cd.setUint32(0, 0x02014b50, true); cd.setUint16(4, 20, true); cd.setUint16(6, 20, true); cd.setUint16(8, 0x0800, true); cd.setUint16(10, 0, true);
    cd.setUint16(12, dosTime, true); cd.setUint16(14, dosDate, true); cd.setUint32(16, crc, true); cd.setUint32(20, data.length, true); cd.setUint32(24, data.length, true);
    cd.setUint16(28, nameB.length, true); cd.setUint16(30, 0, true); cd.setUint16(32, 0, true); cd.setUint16(34, 0, true); cd.setUint16(36, 0, true); cd.setUint32(38, 0, true); cd.setUint32(42, offset, true);
    central.push(new Uint8Array(cd.buffer), nameB);
    offset += 30 + nameB.length + data.length;
  }
  const cdSize = central.reduce((a, b) => a + b.length, 0);
  const end = new DataView(new ArrayBuffer(22));
  end.setUint32(0, 0x06054b50, true); end.setUint16(4, 0, true); end.setUint16(6, 0, true); end.setUint16(8, files.length, true); end.setUint16(10, files.length, true); end.setUint32(12, cdSize, true); end.setUint32(16, offset, true); end.setUint16(20, 0, true);
  return new Blob([...parts, ...central, new Uint8Array(end.buffer)], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

/* ---------- XLSX ---------- */
const xml = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
function sheetXml(rows) {
  const colLetter = (i) => { let s = ''; i++; while (i > 0) { const m = (i - 1) % 26; s = String.fromCharCode(65 + m) + s; i = Math.floor((i - 1) / 26); } return s; };
  const body = rows.map((r, ri) => `<row r="${ri + 1}">${r.map((v, ci) => {
    const ref = `${colLetter(ci)}${ri + 1}`;
    if (typeof v === 'number') return `<c r="${ref}"><v>${v}</v></c>`;
    return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;
  }).join('')}</row>`).join('');
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`;
}
export function workbookBlob(projectId, { approvedOnly = false } = {}) {
  const p = getProject(projectId);
  const ext = getProjectExtractions(projectId).filter(e => !approvedOnly || e.status === 'approved');
  const docs = getProjectDocs(projectId);
  const st = projectStats(p);
  const src = (e) => `${e.source?.docName || ''} · p.${e.source?.page || ''} ¶${e.source?.paragraph || ''}`;
  const sheets = [
    ['Cover', [['VLR Forge — Harmonized Workbook'], ['Project', p.name], ['City', `${p.city}, ${p.country}`], ['Jurisdiction', p.jurisdiction], ['Reporting year', p.year], ['Lifecycle phase', st.phase], ['Completion', `${st.completion}%`], ['Source documents', docs.length], ['Extractions', ext.length], ['Pipeline cost (USD)', Number(projectCost(projectId).toFixed(2))], ['Generated', new Date().toISOString()], ['Generated by', 'VLR Forge V2.4.0']]],
    ['Urban Data', [['SDG', 'Goal', 'Indicator', 'Extraction name', 'Value', 'Unit', 'Year', 'Trend (year:value)', 'AI confidence', 'Review status', 'Source', 'Exact quote', 'City feedback / comments'],
      ...ext.filter(e => e.pillar === 'indicators').map(e => [e.sdg, SDG_TITLES[e.goal] || '', e.indicator || '', e.title, isNaN(Number(e.value)) ? e.value : Number(e.value), e.unit || '', e.year || '', (e.trend || []).map(t => `${t.year}:${t.value}`).join('; '), `${e.confidence}%`, e.status, src(e), quotePlain(e.source?.quote || ''), ''])]],
    ['Documentary', [['SDG target', 'Category', 'Title', 'Summary', 'AI confidence', 'Review status', 'Source', 'Exact quote', 'City feedback / comments'],
      ...ext.filter(e => e.pillar === 'documentary').map(e => [e.sdg, `${e.category} ${e.categoryLabel}`, e.title, e.summary || '', `${e.confidence}%`, e.status, src(e), quotePlain(e.source?.quote || ''), ''])]],
    ['Projects', [['SDG target', 'Project', 'Status', 'Budget', 'Period', 'Lead entity', 'Summary', 'AI confidence', 'Review status', 'Source', 'Exact quote', 'City feedback / comments'],
      ...ext.filter(e => e.pillar === 'projects').map(e => [e.sdg, e.title, e.projectStatus || '', e.budget || '', e.period || '', e.lead || '', e.summary || '', `${e.confidence}%`, e.status, src(e), quotePlain(e.source?.quote || ''), ''])]],
    ['Stakeholders', [['SDG target', 'Category', 'Insight', 'Stakeholder group', 'Engagement type', 'Verbatim quote', 'AI confidence', 'Review status', 'Source', 'City feedback / comments'],
      ...ext.filter(e => e.pillar === 'stakeholders').map(e => [e.sdg, e.category || '', e.title, e.group || '', e.engagement || '', quotePlain(e.source?.quote || ''), `${e.confidence}%`, e.status, src(e), ''])]],
    ['Sources', [['Code', 'Filename', 'Type', 'Language', 'Pages', 'Status', 'Uploaded'], ...docs.map(d => [d.code, d.name, d.type, d.language, d.pages, d.status, fmtLongDate(d.uploadedAt)])]],
  ];
  const files = [
    ['[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],
    ['_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`],
    ['xl/workbook.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([n], i) => `<sheet name="${xml(n)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join('')}</sheets></workbook>`],
    ['xl/_rels/workbook.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join('')}</Relationships>`],
    ...sheets.map(([, rows], i) => [`xl/worksheets/sheet${i + 1}.xml`, sheetXml(rows)]),
  ];
  return zipStored(files);
}

/* ---------- Markdown vault ---------- */
export function markdownVault(projectId) {
  const p = getProject(projectId);
  const ext = getProjectExtractions(projectId);
  const goals = [...new Set(ext.map(e => e.goal))].sort((a, b) => a - b);
  let out = `# ${p.name}\n\n> Generated by VLR Forge V2.4.0 on ${new Date().toISOString()}\n> City: ${p.city}, ${p.country} · Jurisdiction: ${p.jurisdiction} · Reporting year: ${p.year}\n\n`;
  for (const g of goals) {
    out += `## SDG ${g} — ${SDG_TITLES[g]}\n\n`;
    for (const pillar of ['indicators', 'documentary', 'projects', 'stakeholders']) {
      const items = ext.filter(e => e.goal === g && e.pillar === pillar);
      if (!items.length) continue;
      out += `### ${pillar[0].toUpperCase() + pillar.slice(1)}\n\n`;
      for (const e of items) {
        const status = e.status === 'approved' ? '🟢 APPROVED' : e.status === 'rerun_queued' ? '🟠 RERUN' : '🔵 EXTRACTED';
        out += `- **${e.sdg} ${e.title}** ${status}\n`;
        if (e.value) out += `  - Value: ${e.value} ${e.unit || ''} (${e.year || ''})\n`;
        if (e.category) out += `  - Category: ${e.category} ${e.categoryLabel || ''}\n`;
        if (e.summary) out += `  - ${e.summary}\n`;
        out += `  - Source: [[${e.source?.docName}]] · page ${e.source?.page}, paragraph ${e.source?.paragraph}\n  - Quote: "${quotePlain(e.source?.quote || '')}"\n  - AI confidence: ${e.confidence}%\n`;
      }
      out += '\n';
    }
  }
  return out;
}

/* ---------- Printable HTML report ---------- */
export function reportHtml(projectId, { approvedOnly = false, sections = ['indicators', 'documentary', 'projects', 'stakeholders', 'provenance'] } = {}) {
  const p = getProject(projectId);
  const st = projectStats(p);
  const ext = getProjectExtractions(projectId).filter(e => !approvedOnly || e.status === 'approved');
  const docs = getProjectDocs(projectId);
  const sec = (key, title, rows) => sections.includes(key) ? `<h2>${title}</h2>${rows}` : '';
  const table = (head, rows) => `<table><thead><tr>${head.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(p.name)} — VLR Report</title>
  <style>body{font-family:Inter,system-ui,sans-serif;color:#0f172a;margin:48px auto;max-width:900px;padding:0 24px;line-height:1.5}h1{color:#0f2f5c;font-size:32px;margin:0}h2{color:#0f2f5c;border-bottom:2px solid #0f2f5c;padding-bottom:6px;margin-top:36px}h3{color:#1d6fb8}table{border-collapse:collapse;width:100%;font-size:12.5px;margin:12px 0}th,td{border:1px solid #dde5ef;padding:6px 8px;text-align:left;vertical-align:top}th{background:#e9f1fb}blockquote{border-left:3px solid #1d6fb8;margin:8px 0;padding:6px 12px;color:#334155;font-style:italic;background:#f7f9fc}.meta{color:#64748b;font-size:13px}.kpi{display:inline-block;background:#e9f1fb;border:1px solid #cbd9ea;border-radius:8px;padding:10px 16px;margin:12px 12px 0 0}.kpi b{display:block;font-size:22px;color:#0f2f5c}.foot{margin-top:48px;color:#94a3b8;font-size:11px;font-family:monospace}@media print{body{margin:0}}</style></head><body>
  <div class="meta">VOLUNTARY LOCAL REVIEW · ${esc(p.jurisdiction)} · ${p.year}</div>
  <h1>${esc(p.name)}</h1>
  <p class="meta">${esc(p.city)}, ${esc(p.country)} · Lifecycle: ${st.phase} · Generated ${new Date().toLocaleString()} by VLR Forge V2.4.0</p>
  <div><span class="kpi"><b>${docs.length}</b>Source documents</span><span class="kpi"><b>${ext.length}</b>Extractions</span><span class="kpi"><b>${st.completion}%</b>Completion</span><span class="kpi"><b>${fmtCost(projectCost(projectId))}</b>Pipeline cost</span></div>
  ${p.description ? `<h2>Introduction</h2><p>${esc(p.description)}</p>` : ''}
  ${sec('indicators', 'Pillar A — SDG Indicators', ext.filter(e => e.pillar === 'indicators').map(e => `<h3>SDG ${esc(e.sdg)} · ${esc(e.title)}</h3><p><b>${esc(e.value)} ${esc(e.unit || '')}</b> (${e.year || ''}) · AI confidence ${e.confidence}% · ${esc(e.status)}</p><p class="meta">${esc(e.indicator || '')}</p><blockquote>${esc(quotePlain(e.source?.quote || ''))}<br><span class="meta">— ${esc(e.source?.docName)}, page ${e.source?.page}, paragraph ${e.source?.paragraph}</span></blockquote>`).join(''))}
  ${sec('documentary', 'Pillar C — Documentary (Challenges, Commitments, Policies)', table(['SDG', 'Category', 'Title', 'Summary', 'Source'], ext.filter(e => e.pillar === 'documentary').map(e => [esc(e.sdg), esc(`${e.category || ''} ${e.categoryLabel || ''}`), esc(e.title), esc(e.summary || ''), `${esc(e.source?.docName)} p.${esc(e.source?.page)}`])))}
  ${sec('projects', 'Pillar B — Projects & Initiatives', table(['SDG', 'Project', 'Status', 'Budget', 'Period', 'Lead', 'Source'], ext.filter(e => e.pillar === 'projects').map(e => [esc(e.sdg), esc(e.title), esc(e.projectStatus || ''), esc(e.budget || ''), esc(e.period || ''), esc(e.lead || ''), `${esc(e.source?.docName)} p.${esc(e.source?.page)}`])))}
  ${sec('stakeholders', 'Pillar D — Stakeholder Voices', ext.filter(e => e.pillar === 'stakeholders').map(e => `<h3>${esc(e.category)} · ${esc(e.title)}</h3><p class="meta">${esc(e.group)} · ${esc(e.engagement)} · SDG ${esc(e.sdg)}</p><blockquote>${esc(quotePlain(e.source?.quote || ''))}</blockquote>`).join(''))}
  ${sec('provenance', 'Annex — Provenance & Sources', table(['Code', 'Document', 'Type', 'Language', 'Pages', 'Status'], docs.map(d => [esc(d.code), esc(d.name), esc(d.type), esc(d.language), esc(d.pages), esc(d.status)])))}
  <div class="foot">VLR FORGE V2.4.0 · Every value above is traceable to a source document, page and verbatim quote. · ${new Date().toISOString()}</div>
  <script>window.addEventListener('load',()=>setTimeout(()=>window.print(),400));</script>
  </body></html>`;
}

export function reportContentFor(report) {
  const fmt = report.format;
  if (report.bookId) { const { getBook } = storeRef; const book = getBook(report.bookId); if (book) return bookExport(book, fmt === 'docx' ? 'docx' : fmt === 'md' ? 'md' : 'pdf'); }
  const approvedOnly = !!report.approvedOnly;
  if (fmt === 'xlsx') return { blob: workbookBlob(report.projectId, { approvedOnly }), mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', name: report.name };
  if (fmt === 'md') return { blob: new Blob([markdownVault(report.projectId)], { type: 'text/markdown' }), mime: 'text/markdown', name: report.name };
  // pdf / docx → printable HTML in a new tab (user can "Save as PDF")
  return { html: reportHtml(report.projectId, { approvedOnly, sections: report.sections?.length ? report.sections : undefined }), name: report.name };
}


/* ====================================================================== */
/* Final VLR (book) exports: Markdown, printable HTML, and a real .docx     */
/* ====================================================================== */
const plain = (t) => String(t ?? '').replace(/\[\^(\d+)\]/g, '').replace(/\*\*/g, '');
const fnMarks = (t) => (String(t ?? '').match(/\[\^(\d+)\]/g) || []).map(m => m.replace(/\D/g, ''));

function bookChapters(book) { return book.chapterIds.map(getChapter).filter(Boolean).sort((a, b) => a.goal - b.goal); }

/** Flatten a book into a linear list of { kind: 'h1'|'h2'|'h3'|'p'|'box'|'figure'|'table'|'kv'|'list'|'rec'|'signature'|'footnotes'|'pagebreak', ... } */
export function bookOutline(book) {
  const out = [];
  const blocks = (arr) => (arr || []).forEach(b => out.push({ kind: b.type, ...b }));
  out.push({ kind: 'cover', title: book.title, subtitle: book.subtitle });
  book.front.forEach(f => { out.push({ kind: 'h1', text: f.heading, key: f.key }); blocks(f.blocks); (f.subsections || []).forEach(ss => { out.push({ kind: 'h2', text: ss.heading, key: ss.key }); blocks(ss.blocks); }); });
  bookChapters(book).forEach(c => {
    out.push({ kind: 'pagebreak' }); out.push({ kind: 'h1', text: c.title, key: `chapter:${c.id}`, chapterId: c.id });
    c.sections.forEach(s => { out.push({ kind: 'h2', text: `${s.num} ${s.heading}`, key: `${c.id}:${s.key}` }); blocks(s.blocks); (s.subsections || []).forEach(ss => { out.push({ kind: 'h3', text: `${ss.num} ${ss.heading}`, key: `${c.id}:${ss.key}` }); blocks(ss.blocks); }); });
    out.push({ kind: 'footnotes', items: c.footnotes });
  });
  book.back.forEach(f => { out.push({ kind: 'pagebreak' }); out.push({ kind: 'h1', text: f.heading, key: f.key }); blocks(f.blocks); });
  return out;
}

export function bookMarkdown(book) {
  const lines = [];
  for (const it of bookOutline(book)) {
    switch (it.kind) {
      case 'cover': lines.push(`# ${it.title}`, '', `_${it.subtitle}_`, ''); break;
      case 'h1': lines.push('', `# ${it.text}`, ''); break;
      case 'h2': lines.push('', `## ${it.text}`, ''); break;
      case 'h3': lines.push('', `### ${it.text}`, ''); break;
      case 'p': lines.push(it.text, ''); break;
      case 'signature': lines.push(...String(it.text).split('\n').map(x => `_${x}_`), ''); break;
      case 'box': lines.push(`> **${it.title}**`, ...it.items.map(i => `> - ${i.text}${i.fn ? `[^${i.fn}]` : ''}`), ''); break;
      case 'figure': lines.push(`[Image placeholder]`, '', `*${it.caption}*`, ''); break;
      case 'table': lines.push(`**${it.title}**`, '', `| ${it.columns.join(' | ')} |`, `| ${it.columns.map(() => '---').join(' | ')} |`, ...it.rows.map(r => `| ${r.join(' | ')} |`), '', it.source ? `_${it.source}_` : '', ''); break;
      case 'kv': lines.push(...it.rows.map(r => `- **${r[0]}:** ${r[1]}`), ''); break;
      case 'list': lines.push(...it.items.map(i => `- ${i.text}`), ''); break;
      case 'rec': lines.push(`#### ${it.title}`, '', `**Responds to:** ${it.responds}`, '', `**Policy objective:** ${it.objective}`, '', `**Responsible institution:** ${it.lead}`, '', `**Supporting partners:** ${it.partners.join('; ')}`, '', `**Implementation pathway:**`, ...it.pathway.map(x => `- ${x}`), '', `**Indicators and targets:**`, ...it.indicators.map(x => `- ${x}`), '', `**Financing route:** ${it.financing}`, ''); break;
      case 'footnotes': lines.push('', ...it.items.map(f => `[^${f.n}]: ${f.text}`), ''); break;
      case 'pagebreak': lines.push('', '---', ''); break;
      default: break;
    }
  }
  return lines.join('\n');
}

export function bookHtml(book, { print = true } = {}) {
  const fnHtml = (t) => esc(plain(t)) + fnMarks(t).map(n => `<sup>${n}</sup>`).join('');
  const body = bookOutline(book).map(it => {
    switch (it.kind) {
      case 'cover': return `<section class="cover"><div class="eyebrow">Voluntary Local Review</div><h1>${esc(it.title)}</h1><p class="sub">${esc(it.subtitle)}</p></section>`;
      case 'h1': return `<h1>${esc(it.text)}</h1>`; case 'h2': return `<h2>${esc(it.text)}</h2>`; case 'h3': return `<h3>${esc(it.text)}</h3>`;
      case 'p': return `<p>${fnHtml(it.text).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')}</p>`;
      case 'signature': return `<p class="sig">${esc(it.text).replace(/\n/g, '<br>')}</p>`;
      case 'box': return `<div class="box"><div class="box-title">${esc(it.title)}</div><ul>${it.items.map(i => `<li>${esc(i.text)}${i.fn ? `<sup>${i.fn}</sup>` : ''}</li>`).join('')}</ul></div>`;
      case 'figure': return `<figure class="ph"><div class="img">Regional dashboard — image placeholder</div><figcaption>${esc(it.caption)}</figcaption></figure>`;
      case 'table': return `<figure><figcaption>${esc(it.title)}</figcaption><table><thead><tr>${it.columns.map(c => `<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${it.rows.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>${it.source ? `<div class="src">${esc(it.source)}</div>` : ''}</figure>`;
      case 'kv': return `<table class="kv">${it.rows.map(r => `<tr><th>${esc(r[0])}</th><td>${esc(r[1])}</td></tr>`).join('')}</table>`;
      case 'list': return `<ul>${it.items.map(i => `<li>${esc(i.text)}</li>`).join('')}</ul>`;
      case 'rec': return `<div class="rec"><h4>${esc(it.title)}</h4><p><b>Responds to:</b> ${esc(it.responds)}</p><p><b>Policy objective:</b> ${esc(it.objective)}</p><p><b>Responsible institution:</b> ${esc(it.lead)}</p><p><b>Supporting partners:</b> ${esc(it.partners.join('; '))}</p><p><b>Implementation pathway</b></p><ul>${it.pathway.map(x => `<li>${esc(x)}</li>`).join('')}</ul><p><b>Indicators and targets</b></p><ul>${it.indicators.map(x => `<li>${esc(x)}</li>`).join('')}</ul><p><b>Financing route:</b> ${esc(it.financing)}</p></div>`;
      case 'footnotes': return `<section class="fns"><h4>Notes</h4><ol>${it.items.map(f => `<li value="${f.n}">${esc(f.text)}</li>`).join('')}</ol></section>`;
      case 'pagebreak': return `<div class="pb"></div>`;
      default: return '';
    }
  }).join('\n');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(book.title)}</title>
  <style>body{font-family:Georgia,'Times New Roman',serif;color:#111;max-width:820px;margin:48px auto;padding:0 28px;line-height:1.55;font-size:15px}.cover{text-align:center;padding:160px 0 120px;border-bottom:2px solid #0f2f5c;margin-bottom:60px}.cover .eyebrow{font-family:Inter,Arial,sans-serif;letter-spacing:.2em;text-transform:uppercase;color:#1d6fb8;font-size:12px}.cover h1{font-size:40px;color:#0f2f5c;margin:16px 0 8px}.cover .sub{color:#555;font-size:17px}h1{font-family:Inter,Arial,sans-serif;color:#0f2f5c;font-size:26px;margin-top:40px}h2{font-family:Inter,Arial,sans-serif;color:#0f2f5c;font-size:19px;margin-top:30px}h3{font-family:Inter,Arial,sans-serif;color:#1d6fb8;font-size:16px;margin-top:22px}h4{font-family:Inter,Arial,sans-serif;font-size:14px;margin-top:18px}sup{font-size:10px;color:#1d6fb8}.box{border:1px solid #cbd9ea;background:#eef5fd;padding:12px 16px;margin:16px 0;font-family:Inter,Arial,sans-serif;font-size:13.5px}.box-title{font-weight:700;color:#0f2f5c;margin-bottom:6px}.ph .img{height:180px;background:repeating-linear-gradient(45deg,#f1f5f9,#f1f5f9 10px,#e2e8f0 10px,#e2e8f0 20px);display:grid;place-items:center;color:#64748b;font-family:Inter,Arial,sans-serif;font-size:12px;border:1px solid #cbd5e1}figure{margin:18px 0}figcaption{font-family:Inter,Arial,sans-serif;font-size:12.5px;font-weight:700;color:#0f2f5c;margin:6px 0}table{border-collapse:collapse;width:100%;font-family:Inter,Arial,sans-serif;font-size:12.5px}th,td{border:1px solid #cbd5e1;padding:6px 9px;text-align:left}th{background:#e9f1fb}.src{font-size:11px;color:#64748b;margin-top:4px}.kv th{width:32%;background:#f8fafc}.rec{border-left:3px solid #0f2f5c;padding:4px 16px;margin:16px 0;background:#f8fafc}.fns{margin-top:28px;border-top:1px solid #cbd5e1;padding-top:10px;font-size:11.5px;color:#334155}.fns h4{margin:0 0 6px}.sig{font-style:italic;color:#334155}.pb{page-break-after:always}@media print{body{margin:0;max-width:none}}</style></head>
  <body>${body}${print ? '<script>window.addEventListener("load",()=>setTimeout(()=>window.print(),500));</script>' : ''}</body></html>`;
}

/* ---------- minimal DOCX writer (WordprocessingML, stored zip) ---------- */
const wx = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const run = (t, { b = false, i = false, sup = false, size } = {}) => `<w:r><w:rPr>${b ? '<w:b/>' : ''}${i ? '<w:i/>' : ''}${sup ? '<w:vertAlign w:val="superscript"/>' : ''}${size ? `<w:sz w:val="${size}"/>` : ''}</w:rPr><w:t xml:space="preserve">${wx(t)}</w:t></w:r>`;
const para = (runs, { style, align, spacingAfter = 120 } = {}) => `<w:p><w:pPr>${style ? `<w:pStyle w:val="${style}"/>` : ''}${align ? `<w:jc w:val="${align}"/>` : ''}<w:spacing w:after="${spacingAfter}"/></w:pPr>${runs}</w:p>`;
const richRuns = (text) => {
  // **bold** and [^n] footnote markers
  const out = []; const parts = String(text ?? '').split(/(\*\*[^*]+\*\*|\[\^\d+\])/g);
  for (const p of parts) { if (!p) continue; if (/^\*\*/.test(p)) out.push(run(p.replace(/\*\*/g, ''), { b: true })); else if (/^\[\^/.test(p)) out.push(run(p.replace(/\D/g, ''), { sup: true })); else out.push(run(p)); }
  return out.join('');
};
const tbl = (columns, rows) => `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="0" w:type="auto"/><w:tblBorders>${['top', 'left', 'bottom', 'right', 'insideH', 'insideV'].map(s => `<w:${s} w:val="single" w:sz="4" w:space="0" w:color="CBD5E1"/>`).join('')}</w:tblBorders></w:tblPr><w:tblGrid>${columns.map(() => '<w:gridCol w:w="2400"/>').join('')}</w:tblGrid><w:tr>${columns.map(c => `<w:tc><w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="E9F1FB"/></w:tcPr>${para(run(c, { b: true, size: 20 }), { spacingAfter: 40 })}</w:tc>`).join('')}</w:tr>${rows.map(r => `<w:tr>${r.map(c => `<w:tc>${para(run(c, { size: 20 }), { spacingAfter: 40 })}</w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>${para('', { spacingAfter: 120 })}`;

export function bookDocxBlob(book) {
  const body = [];
  for (const it of bookOutline(book)) {
    switch (it.kind) {
      case 'cover': body.push(para(run('VOLUNTARY LOCAL REVIEW', { size: 22 }), { align: 'center', spacingAfter: 600 }), para(run(it.title, { b: true, size: 56 }), { style: 'Title', align: 'center', spacingAfter: 200 }), para(run(it.subtitle, { i: true, size: 26 }), { align: 'center', spacingAfter: 2400 }), `<w:p><w:r><w:br w:type="page"/></w:r></w:p>`); break;
      case 'h1': body.push(para(run(it.text, { b: true }), { style: 'Heading1', spacingAfter: 200 })); break;
      case 'h2': body.push(para(run(it.text, { b: true }), { style: 'Heading2', spacingAfter: 160 })); break;
      case 'h3': body.push(para(run(it.text, { b: true }), { style: 'Heading3', spacingAfter: 120 })); break;
      case 'p': body.push(para(richRuns(it.text))); break;
      case 'signature': body.push(...String(it.text).split('\n').map(x => para(run(x, { i: true }), { spacingAfter: 40 }))); break;
      case 'box': body.push(para(run(it.title, { b: true }), { style: 'Heading4', spacingAfter: 60 }), ...it.items.map(i => para(run('• ' + i.text + (i.fn ? ` [${i.fn}]` : ''), { size: 21 }), { spacingAfter: 60 }))); break;
      case 'figure': body.push(para(run('[Image placeholder — regional dashboard]', { i: true }), { align: 'center', spacingAfter: 40 }), para(run(it.caption, { b: true, size: 20 }), { align: 'center' })); break;
      case 'table': body.push(para(run(it.title, { b: true, size: 20 }), { spacingAfter: 60 }), tbl(it.columns, it.rows), ...(it.source ? [para(run(it.source, { i: true, size: 18 }))] : [])); break;
      case 'kv': body.push(tbl(['Item', 'Value'], it.rows)); break;
      case 'list': body.push(...it.items.map(i => para(run('• ' + i.text), { spacingAfter: 60 }))); break;
      case 'rec': body.push(para(run(it.title, { b: true }), { style: 'Heading4' }), para(richRuns(`**Responds to:** ${it.responds}`)), para(richRuns(`**Policy objective:** ${it.objective}`)), para(richRuns(`**Responsible institution:** ${it.lead}`)), para(richRuns(`**Supporting partners:** ${it.partners.join('; ')}`)), para(run('Implementation pathway', { b: true }), { spacingAfter: 40 }), ...it.pathway.map(x => para(run('• ' + x), { spacingAfter: 40 })), para(run('Indicators and targets', { b: true }), { spacingAfter: 40 }), ...it.indicators.map(x => para(run('• ' + x), { spacingAfter: 40 })), para(richRuns(`**Financing route:** ${it.financing}`))); break;
      case 'footnotes': body.push(para(run('Notes', { b: true, size: 20 }), { spacingAfter: 60 }), ...it.items.map(f => para(run(`${f.n}. ${f.text}`, { size: 18 }), { spacingAfter: 40 }))); break;
      case 'pagebreak': body.push(`<w:p><w:r><w:br w:type="page"/></w:r></w:p>`); break;
      default: break;
    }
  }
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body.join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr></w:body></w:document>`;
  const styles = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Georgia" w:hAnsi="Georgia"/><w:sz w:val="22"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="300" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
  <w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:color w:val="0F2F5C"/><w:sz w:val="56"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="360" w:after="200"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:color w:val="0F2F5C"/><w:sz w:val="36"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="280" w:after="160"/><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:color w:val="0F2F5C"/><w:sz w:val="28"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading3"><w:name w:val="heading 3"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="200" w:after="120"/><w:outlineLvl w:val="2"/></w:pPr><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:color w:val="1D6FB8"/><w:sz w:val="24"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading4"><w:name w:val="heading 4"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="160" w:after="80"/><w:outlineLvl w:val="3"/></w:pPr><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:sz w:val="22"/></w:rPr></w:style>
  <w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideH w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideV w:val="single" w:sz="4" w:space="0" w:color="auto"/></w:tblBorders></w:tblPr></w:style></w:styles>`;
  const files = [
    ['[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`],
    ['_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`],
    ['word/_rels/document.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],
    ['word/document.xml', document],
    ['word/styles.xml', styles],
  ];
  const blob = zipStored(files);
  return new Blob([blob], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
}

/** Content for a book export by format ('docx' | 'md' | 'pdf'). */
export function bookExport(book, format) {
  const p = getProject(book.projectId);
  const base = `${p?.city || 'City'}_${p?.year || ''}_VLR_v${book.version}`;
  if (format === 'docx') return { blob: bookDocxBlob(book), mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', name: `${base}.docx` };
  if (format === 'md') return { blob: new Blob([bookMarkdown(book)], { type: 'text/markdown' }), mime: 'text/markdown', name: `${base}.md` };
  return { html: bookHtml(book), name: `${base}.pdf` };
}
